# 10차시 정답 Notebook — 모델 평가와 새 데이터 예측

## 1단계. 9차시 모델 다시 만들기

> ⚠️ **부호 규약을 다시 확인하세요 — 9차시와 같은 약속을 그대로 씁니다.**
>
> 1~8차시의 `합격여부`는 `1`이 **합격**, `-1`이 불합격이었지만,
> 9·10차시의 `검사결과`는 **`0`=합격, `1`=불합격**입니다.
> 같은 `1`의 의미가 정반대로 뒤집힙니다.
>
> 오늘 만드는 `예측_검사결과`도 같은 약속을 따릅니다 — `1`로 예측된 로트가 **불합격 위험** 로트입니다.
> 4단계에서 구하는 `불합격_확률`이 `predict_proba`의 **1번 열**인 것도 같은 이유입니다.
> 숫자를 읽기 전에 "지금 어느 쪽이 합격이지?"를 한 번씩 확인하세요.

In [1]:
# 오늘 쓸 도구(pandas, scikit-learn)를 불러오고, 9차시 학습 데이터를 읽어 df에 저장합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 결측값이 있는 행을 지운 뒤 몇 행이 남았는지 확인해 보세요.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# .dropna(): 빈칸(결측값)이 하나라도 있는 행을 지웁니다(5차시). 9차시와 똑같이 지워야 같은 모델이 만들어집니다.
df = pd.read_csv("../../data/weekly/week09/week09_pass_fail_train.csv").dropna()
print(df.shape)  # (중간 확인)

(735, 9)

In [2]:
# 모델에 넣을 특징(Feature) 열 6개의 이름을 feature_cols에 담고, 문제(X)와 정답(y)을 나눕니다.
# 정답 열 검사결과는 0 = 합격, 1 = 불합격입니다. 실행하면 X의 앞 5행이 보입니다 — 열이 6개인지 확인해 보세요.
feature_cols = ["온도_섭씨", "압력_Pa", "가스유량_slm", "두께_nm", "진공도_mTorr", "습도_pct"]
X = df[feature_cols]
y = df["검사결과"]
X.head()  # (중간 확인)

   온도_섭씨   압력_Pa  가스유량_slm   두께_nm  진공도_mTorr  습도_pct
0  300.0   997.3     53.67  100.51       5.50    49.8
1  294.6  1018.2     50.88   95.48       4.61    42.7
2  299.6   996.3     51.55   98.23       5.46    53.8
3  307.2  1028.8     52.35  102.23       5.02    45.9
4  296.6  1017.8     50.85   95.13       5.04    43.5

In [3]:
# 9차시와 똑같은 설정으로 데이터를 학습용(train) 80%와 평가용(test) 20%로 나눕니다.
# random_state=42가 같으면 언제 실행해도 똑같이 나뉘고, stratify=y는 합격·불합격 비율을 양쪽에 똑같이 맞춥니다.
# 실행하면 학습용·평가용 행 개수가 출력됩니다 — 평가용이 9차시와 같은 147건인지 확인해 보세요.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(len(X_train), len(X_test))  # (중간 확인)

588 147

In [4]:
# 깊이가 최대 4인 결정 트리 모델을 만들고, 학습용 데이터로 학습(fit)시킵니다.
# 실행하면 모델 이름과 설정(max_depth=4, random_state=42)이 한 줄로 보입니다 — 학습이 끝났다는 뜻입니다.
model = DecisionTreeClassifier(max_depth=4, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

## 2단계. 새 로트 불러오기

In [5]:
# 아직 검사 결과가 나오지 않은 새 로트 CSV를 읽어 new_lots에 저장합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 새 로트가 몇 건인지, 학습 데이터보다 열이 몇 개 적은지 확인해 보세요.
new_lots = pd.read_csv("../../data/weekly/week09/week09_new_lots_to_predict.csv")
print(new_lots.shape)  # (중간 확인)

(9, 8)

In [6]:
# 새 로트에서 학습 때와 똑같은 특징 열 6개(feature_cols)만 골라 X_new에 저장합니다.
# 열 이름·순서가 학습 때와 같아야 모델이 예측할 수 있습니다. 실행하면 9행 6열 표가 보입니다 — 진공도_mTorr 값도 훑어보세요.
X_new = new_lots[feature_cols]
X_new  # (중간 확인)

   온도_섭씨   압력_Pa  가스유량_slm   두께_nm  진공도_mTorr  습도_pct
0  294.5  1005.1     50.04   96.46       4.02    44.4
1  301.5  1007.2     55.68  100.65       5.38    46.8
2  289.8  1009.2     50.69   96.19       5.14    42.0
3  295.6  1019.5     49.10   98.97       4.96    44.6
4  299.1  1026.4     56.25  103.10       4.86    38.8
5  302.0  1026.1     51.59  103.76       4.81    50.9
6  305.2  1005.6     47.16  101.69       4.35    42.7
7  299.1   989.2     54.12   98.41       5.09    49.3
8  300.6  1031.7     49.89  102.78       4.54    41.2

## 3단계. 새 로트 예측하기

In [7]:
# 학습한 모델에 새 로트를 넣어 합격(0)/불합격(1)을 예측하고, 그 결과를 예측_검사결과라는 새 열에 저장합니다.
# 실행하면 로트 9건의 공정명·설비번호·온도와 예측 결과가 보입니다 — 1(불합격)로 예측된 로트가 있는지 확인해 보세요.
new_lots["예측_검사결과"] = model.predict(X_new)
print(new_lots[["공정명", "설비번호", "온도_섭씨", "예측_검사결과"]])

  공정명   설비번호  온도_섭씨  예측_검사결과
0  식각  EQ-02  294.5        0
1  산화  EQ-02  301.5        0
2  식각  EQ-04  289.8        0
3  포토  EQ-04  295.6        0
4  식각  EQ-04  299.1        0
5  포토  EQ-03  302.0        0
6  산화  EQ-01  305.2        0
7  산화  EQ-03  299.1        0
8  세정  EQ-01  300.6        0

## 4단계. 확률까지 확인하기

In [8]:
# 예측 결과 대신 "각 결과일 확률"을 계산해 proba에 저장합니다. 로트마다 [합격일 확률, 불합격일 확률] 두 숫자가 나옵니다.
# 실행하면 9행 2열 숫자 표가 보입니다 — 한 행의 두 숫자를 더하면 1이 되는지 확인해 보세요.
proba = model.predict_proba(X_new)   # [합격일 확률, 불합격일 확률]
proba.round(3)  # (중간 확인)

array([[0.636, 0.364],
       [0.933, 0.067],
       [0.842, 0.158],
       [0.933, 0.067],
       [0.933, 0.067],
       [0.933, 0.067],
       [0.636, 0.364],
       [0.933, 0.067],
       [0.933, 0.067]])

In [9]:
# proba[:, 1]로 모든 행(:)의 1번 열(불합격일 확률)만 꺼내, 소수 셋째 자리까지 반올림해 불합격_확률 열에 저장합니다.
# 실행하면 예측_검사결과 옆에 불합격_확률이 붙은 표가 보입니다 — 예측이 같은 로트끼리도 확률이 다른지 비교해 보세요.
new_lots["불합격_확률"] = proba[:, 1].round(3)

print(new_lots[["공정명", "설비번호", "온도_섭씨", "예측_검사결과", "불합격_확률"]])

  공정명   설비번호  온도_섭씨  예측_검사결과  불합격_확률
0  식각  EQ-02  294.5        0   0.364
1  산화  EQ-02  301.5        0   0.067
2  식각  EQ-04  289.8        0   0.158
3  포토  EQ-04  295.6        0   0.067
4  식각  EQ-04  299.1        0   0.067
5  포토  EQ-03  302.0        0   0.067
6  산화  EQ-01  305.2        0   0.364
7  산화  EQ-03  299.1        0   0.067
8  세정  EQ-01  300.6        0   0.067

### 확인하기 — proba[:, 1]이 왜 "불합격 확률"일까?
강의 「체크포인트 — proba[:, 1]이 항상 "불합격 확률"은 아니다」의 확인 코드입니다. `predict_proba`가 돌려주는 열의 순서는 `model.classes_`에 적힌 순서를 따릅니다. 새로운 데이터를 다룰 때는 이 순서를 먼저 확인하는 습관을 들이세요.

In [10]:
# 모델이 구분하는 결과(클래스)의 순서를 출력합니다. predict_proba의 열 순서가 이 순서를 따릅니다.
# 실행하면 대괄호 안에 값 두 개가 보입니다 — 앞쪽이 0번 열, 뒤쪽이 1번 열입니다. 1번 열이 1(불합격)인지 확인해 보세요.
print(model.classes_)

[0 1]

## 5단계. 가장 위험한 로트 찾기

In [11]:
# 불합격_확률이 큰 순서(내림차순)로 표를 정렬하고 맨 위 2개 로트를 riskiest에 저장합니다(sort_values, 4차시 복습).
# 힌트: 확률이 똑같은 로트가 두 개 나올 수도 있습니다. 그럴 때는 둘 다 답입니다.
# 실행하면 불합격 확률이 가장 높은 로트 2개가 보입니다 — 어느 공정·설비의 로트인지 확인해 보세요.
riskiest = new_lots.sort_values("불합격_확률", ascending=False).head(2)
print(riskiest[["공정명", "설비번호", "온도_섭씨", "불합격_확률"]])

  공정명   설비번호  온도_섭씨  불합격_확률
0  식각  EQ-02  294.5   0.364
6  산화  EQ-01  305.2   0.364

## 6단계(회고). 10차시 되짚기

> 가장 기억에 남는 차시와 이유: 9차시 — 정확도가 기준선보다 낮게 나왔는데도 혼동행렬을 보면 의미가 있다는 것을 배운 순간이 가장 인상적이었다.

> 더 공부하고 싶은 주제: 더 다양한 분류 모델(로지스틱 회귀, 랜덤 포레스트 등)과 성능을 어떻게 더 끌어올릴 수 있을지 알아보고 싶다.

### 도전 문제 1 — 더 깊은 트리로 다시 예측하기 (빠른 학습자용)
강의 자료 「도전 실습」 절의 도전 문제입니다. 9차시 모델보다 더 깊은(더 복잡한) 결정 트리를 같은 학습용 데이터로 다시 학습시킨 뒤, 같은 새 로트 9건의 예측 결과와 불합격 확률이 달라지는지 비교합니다. 마지막에는 두 모델의 test 정확도를 비교해 "더 복잡한 모델이 항상 더 좋은가?"를 확인합니다. 네 셀을 차례로 실행하며 중간 결과를 확인하세요.

In [12]:
# 도전 문제 1-①: 강의 도전 문제가 정한 깊이로 새 결정 트리 model2를 만들고, 1단계와 같은 학습용 데이터(X_train, y_train)로 학습시킵니다.
# 1단계의 model은 그대로 두고 이름만 다른 새 모델을 하나 더 만드는 것입니다. 실행하면 model2의 이름과 설정이 한 줄로 보입니다.
model2 = DecisionTreeClassifier(max_depth=8, random_state=42)
model2.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=8, random_state=42)

> **참고**
>
> - 빈칸(인자=값): 강의 자료 「도전 실습」 절의 도전 문제 첫 문장에, 9차시 모델을 어떤 설정으로 다시 학습시킬지 `인자=값` 모양 그대로 적혀 있습니다. 1단계 셀에서 `max_depth=4`가 있던 자리입니다.
> - `max_depth`는 결정 트리가 갈래(질문)를 최대 몇 번까지 이어 갈지 정하는 값입니다. 값이 클수록 학습 데이터에 더 세밀하게 맞춘, 더 복잡한 트리가 됩니다.
>
> 정답 해설: `max_depth=8`을 넣었다. 강의 도전 문제가 정한 깊이로, 1단계 모델(`max_depth=4`)보다 최대 깊이가 4에서 8로 두 배가 된 트리다. `random_state=42`는 1단계와 같게 두어 깊이만 다르게 했다.

In [13]:
# 도전 문제 1-②: 새로 학습한 model2로 새 로트 9건(X_new)의 합격(0)/불합격(1)을 다시 예측해 출력합니다.
# 실행하면 0과 1이 9개 한 줄로 보입니다 — 3단계에서 model이 9건 모두 0(합격)으로 예측했던 것과 달라진 로트가 있는지 보세요.
print(model2.predict(X_new))

[1 0 0 0 0 0 0 0 0]

> **참고**
>
> - 빈칸(메서드 이름): 강의 자료 「① 파이썬으로 새 로트 예측하기」 절의 「새 로트 불러와서 예측하기」 코드와 「핵심 용어 카드」 첫 번째 카드에 나오는, 학습된 모델에 새 데이터를 넣어 예측값(0/1)을 얻는 메서드입니다. 3단계에서 `model`에 쓴 것과 같은 메서드를 이번에는 `model2`에 씁니다.
> - 결과는 새 로트 순서대로 0(합격) 또는 1(불합격)이 하나씩 나옵니다.
>
> 정답 해설: `predict`를 넣었다. `model2.predict(X_new)`는 3단계의 `model.predict(X_new)`와 같은 일을 깊이 8짜리 모델로 한다.

In [14]:
# 도전 문제 1-③: 두 모델의 불합격 확률을 나란히 비교합니다. new_lots를 바꾸지 않도록 .copy()로 복사본(compare)을 만들어 씁니다.
# 실행하면 불합격_확률(1단계 model)과 불합격_확률_model2(새 모델)가 나란히 보입니다 — 새 모델의 확률이 0이나 1 쪽으로 쏠리는지 보세요.
compare = new_lots[["공정명", "설비번호", "불합격_확률"]].copy()
compare["불합격_확률_model2"] = model2.predict_proba(X_new)[:, 1].round(3)
print(compare)

  공정명   설비번호  불합격_확률  불합격_확률_model2
0  식각  EQ-02   0.364          1.000
1  산화  EQ-02   0.067          0.044
2  식각  EQ-04   0.158          0.000
3  포토  EQ-04   0.067          0.044
4  식각  EQ-04   0.067          0.044
5  포토  EQ-03   0.067          0.044
6  산화  EQ-01   0.364          0.053
7  산화  EQ-03   0.067          0.044
8  세정  EQ-01   0.067          0.044

> **참고**
>
> - 빈칸(메서드 이름): 강의 자료 「① 파이썬으로 새 로트 예측하기」 절의 「확률까지 함께 보기」 소제목 아래 코드와 「핵심 용어 카드」 두 번째 카드에 나오는, 각 클래스(합격/불합격)일 확률을 돌려주는 메서드입니다. 4단계에서 `model`에 쓴 것과 같은 메서드입니다.
> - 뒤의 `[:, 1]`은 모든 행의 1번 열, 즉 불합격일 확률만 꺼냅니다(강의 「체크포인트 — proba[:, 1]이 항상 "불합격 확률"은 아니다」). `.round(3)`은 소수 셋째 자리까지 반올림합니다.
>
> 정답 해설: `predict_proba`를 넣었다. 돌려받은 9행 2열 확률 표에서 `[:, 1]`로 불합격 확률만 꺼내 새 열에 저장했다.

In [15]:
# 도전 문제 1-④: 두 모델의 test 정확도를 비교합니다. model.score(X_test, y_test)는 평가용 데이터에서 맞힌 비율(정확도)입니다(9차시).
# 실행하면 두 모델의 깊이와 test 정확도가 한 줄씩 출력됩니다 — 더 복잡한(깊은) 모델이 정말 더 정확한지 확인해 보세요.
# model.max_depth: 모델을 만들 때 넣은 깊이 값을 다시 꺼내 봅니다.
print(f"max_depth={model.max_depth} test 정확도: {model.score(X_test, y_test):.1%}")
print(f"max_depth={model2.max_depth} test 정확도: {model2.score(X_test, y_test):.1%}")

max_depth=4 test 정확도: 78.2%
max_depth=8 test 정확도: 75.5%

**도전 문제 정리**: 위 네 셀에서 예측 결과·불합격 확률·test 정확도가 어떻게 달라졌는지 보고, "더 복잡한 모델이 항상 더 좋은 것은 아니다"를 9차시에서 배운 내용과 연결해 한 문장으로 적어 보세요.

**예시 답안**: 깊이 8 모델은 0번 로트를 불합격으로 바꾸고 확률도 0과 1 쪽으로 강하게 쏠렸지만, test 정확도는 78.2%에서 75.5%로 오히려 낮아졌다. 학습 데이터에 더 딱 맞춘 복잡한 모델이 처음 보는 데이터에서도 더 잘 맞는 것은 아니므로, 9차시처럼 test 데이터로 확인해야 한다.

## 7단계. AI에게 질문하며 더 알아보기
10차시 마지막 실습입니다. 오늘 배운 예측·확률에 대해 AI 챗봇에게 질문해 이해를 넓혀봅니다.

질문 예시:
- "predict()와 predict_proba()는 내부적으로 어떻게 다른 계산을 하나요?"
- "학습시킨 모델을 저장했다가 나중에 다시 불러와서 쓰려면 어떻게 하나요?"
- "새 데이터가 학습 데이터 범위를 벗어나면 예측이 부정확해질 수 있다는데, 왜 그런가요?"
- "시간이 지나며 모델 성능이 떨어지는 현상을 뭐라고 부르나요?"

## 8단계. AI에게 코드 생성 요청하고 직접 실행해보기
프롬프트 예시: "로트 이름과 불합격 확률 리스트를 받아서, 확률이 높은 순서로 정렬하고 위험도
등급(높음/보통/낮음)을 함께 표시하는 코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드와 실행 결과입니다.

### AI 예시 코드를 오늘 새 로트에 적용해 보기
강의의 AI 예시 코드는 로트 이름(LOT-A~D)을 지어내고 불합격 확률 4개를 직접 적어 넣었습니다. 같은 반복문에 오늘 만든 `new_lots`의 이름표와 `불합격_확률` 열을 넣으면 새 로트 9건 전체의 위험도를 매길 수 있습니다. 위험도 기준(0.3, 0.15)은 여전히 AI가 임의로 정한 값입니다.

In [16]:
# AI가 만들어 줄 수 있는 코드 예시입니다. 로트 이름 4개와 불합격 확률 4개(예시 값)를 짝지어, 확률이 높은 순서로 위험도를 붙입니다.
# 실행하면 로트 4개가 위험도(높음/보통/낮음)와 함께 출력됩니다. 위험도 기준(0.3, 0.15)은 AI가 임의로 정한 값입니다.
lots = ["LOT-A", "LOT-B", "LOT-C", "LOT-D"]
fail_proba = [0.364, 0.067, 0.158, 0.067]

# zip(A, B): 두 리스트에서 같은 순서의 값을 짝지어 줍니다.
# sorted(..., key=lambda x: x[1], reverse=True): 짝의 두 번째 값(확률)이 큰 것부터 정렬합니다.
for lot, p in sorted(zip(lots, fail_proba), key=lambda x: x[1], reverse=True):
    if p >= 0.3:
        risk = "높음"
    elif p >= 0.15:
        risk = "보통"
    else:
        risk = "낮음"
    # {p:.1%}: 0.364 같은 소수를 36.4%처럼 백분율(소수 첫째 자리)로 바꿔 보여 줍니다.
    print(f"{lot}: 불합격 확률 {p:.1%} → 위험도 {risk}")

LOT-A: 불합격 확률 36.4% → 위험도 높음
LOT-C: 불합격 확률 15.8% → 위험도 보통
LOT-B: 불합격 확률 6.7% → 위험도 낮음
LOT-D: 불합격 확률 6.7% → 위험도 낮음

In [17]:
# AI 예시의 지어낸 로트 이름 대신, 새 로트 9건에 "공정명-설비번호" 형태의 이름표를 붙입니다(글자 열끼리 +로 이어 붙임).
# 실행하면 이름표 9개가 보입니다 — 로트 번호가 따로 없어서 같은 이름표가 두 번 나오는 곳이 있는지 확인해 보세요.
labels = new_lots["공정명"] + "-" + new_lots["설비번호"]
labels  # (중간 확인)

0    식각-EQ-02
1    산화-EQ-02
2    식각-EQ-04
3    포토-EQ-04
4    식각-EQ-04
5    포토-EQ-03
6    산화-EQ-01
7    산화-EQ-03
8    세정-EQ-01
dtype: object

In [18]:
# 위 AI 예시 코드의 반복문을 그대로 쓰되, lots·fail_proba 대신 labels와 4단계의 불합격_확률 열을 넣습니다.
# 실행하면 새 로트 9건이 확률이 높은 순서로 위험도와 함께 출력됩니다 — "높음"인 로트가 5단계의 두 로트와 같은지 확인해 보세요.
for lot, p in sorted(zip(labels, new_lots["불합격_확률"]), key=lambda x: x[1], reverse=True):
    if p >= 0.3:
        risk = "높음"
    elif p >= 0.15:
        risk = "보통"
    else:
        risk = "낮음"
    print(f"{lot}: 불합격 확률 {p:.1%} → 위험도 {risk}")

식각-EQ-02: 불합격 확률 36.4% → 위험도 높음
산화-EQ-01: 불합격 확률 36.4% → 위험도 높음
식각-EQ-04: 불합격 확률 15.8% → 위험도 보통
산화-EQ-02: 불합격 확률 6.7% → 위험도 낮음
포토-EQ-04: 불합격 확률 6.7% → 위험도 낮음
식각-EQ-04: 불합격 확률 6.7% → 위험도 낮음
포토-EQ-03: 불합격 확률 6.7% → 위험도 낮음
산화-EQ-03: 불합격 확률 6.7% → 위험도 낮음
세정-EQ-01: 불합격 확률 6.7% → 위험도 낮음

## 9단계. 연습문제 — 위험 로트 개수 세기
불합격_확률이 0.5를 초과하는(50%보다 큰) 로트를 "위험 로트"로 정의하고, 몇 개인지
세어봅니다(4차시에서 배운 조건 검색 복습).

In [19]:
# 불합격_확률이 0.5보다 큰 로트만 골라 risky_lots에 저장하고, len()으로 개수를 셉니다(4차시 조건 검색 복습).
# 실행하면 위험 로트 개수가 출력됩니다 — 0개가 나와도 코드가 틀린 것은 아닙니다. "해당하는 것이 없다"도 분석 결과입니다.
risky_lots = new_lots[new_lots["불합격_확률"] > 0.5]
print(f"위험 로트(불합격 확률 50% 초과) 개수: {len(risky_lots)}개")

위험 로트(불합격 확률 50% 초과) 개수: 0개

### 기준을 0.3으로 낮춰 보기
강의 연습문제 「정답 보기」에 나오는 확인 코드입니다. 같은 데이터라도 "위험 로트"의 기준을 어디에 두느냐에 따라 결과가 달라지는지 확인합니다(실습지 8번 심화 실습으로 이어집니다).

In [20]:
# 기준을 0.3으로 낮춰, 불합격_확률이 0.3 이상(>=)인 로트만 골라 봅니다.
# 실행하면 조건에 맞는 로트의 행이 표로 보입니다 — 0.5 기준일 때와 개수가 어떻게 달라졌는지 비교해 보세요.
new_lots[new_lots["불합격_확률"] >= 0.3]

,공정명,설비번호,온도_섭씨,압력_Pa,가스유량_slm,두께_nm,진공도_mTorr,습도_pct,예측_검사결과,불합격_확률
0,식각,EQ-02,294.5,1005.1,50.04,96.46,4.02,44.4,0,0.364
6,산화,EQ-01,305.2,1005.6,47.16,101.69,4.35,42.7,0,0.364

## 10단계. AI로 재미있는 미니 프로그램 만들기 🎉 — 10차시 완주 인증서 만들기
프롬프트 예시: "input()으로 이름을 입력받고, 이모지나 별표(*)로 테두리를 두른 '10차시
반도체 데이터 분석 과정 수료증'을 이름과 함께 예쁘게 출력하는 파이썬 코드를 만들어줘."

In [21]:
# AI가 만들어 줄 수 있는 수료증 코드 예시입니다. 원래는 input()으로 이름을 입력받지만, 자동 실행을 위해 예시 이름을 넣었습니다.
# 실행하면 이모지 테두리를 두른 수료증이 출력됩니다 — name에 자기 이름을 넣고 다시 실행해 보세요.
name = "지민"  # 실제로는 input("이름을 입력하세요: ")

# 문자열 * 숫자: 문자열을 그 횟수만큼 반복해 이어 붙입니다.
print("🎓" * 15)
print("   10차시 반도체 데이터 분석 과정 수료증")
print("   위 사람은 10차시 전체 과정을 성실히 마쳤음을 증명합니다.")
print(f"   이름: {name}")
print("🎓" * 15)

🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓
   10차시 반도체 데이터 분석 과정 수료증
   위 사람은 10차시 전체 과정을 성실히 마쳤음을 증명합니다.
   이름: 지민
🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓🎓