# 4차시 실습 — Pandas 가장 기본적인 부분 (정답)

데이터: `week04_process_filtering.csv`(교육용 가상 데이터, 100행 8열). `합격여부`는 1 = 합격, -1 = 불합격.

## 1단계. 데이터 읽기

In [1]:
import pandas as pd

df = pd.read_csv("../../data/weekly/week04/week04_process_filtering.csv", encoding="utf-8-sig")
df.head()

               측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
0  2024-03-01 21:00  LOT-0141  EQ-02  산화  297.6  1005.8     50.02     1
1  2024-03-02 04:00  LOT-0122  EQ-04  식각  300.4  1010.5     49.22     1
2  2024-03-02 08:00  LOT-0156  EQ-02  세정  296.9  1007.6     50.91    -1
3  2024-03-02 12:00  LOT-0224  EQ-02  산화  297.2  1019.1     47.75     1
4  2024-03-02 21:00  LOT-0302  EQ-01  세정  296.7  1016.9     51.17     1

## 2단계. 표의 크기와 열 이름 확인하기

In [2]:
print(df.shape)

(100, 8)

In [3]:
print(df.columns)

Index(['측정시간', '로트번호', '설비번호', '공정명', '온도_섭씨', '압력_Pa', '가스유량_slm', '합격여부'], dtype='str')

## 3단계. 열 선택하기

In [4]:
print(df["온도_섭씨"].head())

0    297.6
1    300.4
2    296.9
3    297.2
4    296.7
Name: 온도_섭씨, dtype: float64

### 여러 열 함께 꺼내기

In [5]:
print(df[["설비번호", "온도_섭씨", "합격여부"]].head())

# print(df["설비번호", "온도_섭씨", "합격여부"])  # 주석을 풀면 KeyError: 대괄호를 한 겹만 썼다

    설비번호  온도_섭씨  합격여부
0  EQ-02  297.6     1
1  EQ-04  300.4     1
2  EQ-02  296.9    -1
3  EQ-02  297.2     1
4  EQ-01  296.7     1

## 4단계. 조건 검색 — 특정 설비만 찾기

In [6]:
check = df["설비번호"] == "EQ-02"
print(check.head())

0     True
1    False
2     True
3     True
4    False
Name: 설비번호, dtype: bool

### True인 행만 남기기

In [7]:
eq02 = df[df["설비번호"] == "EQ-02"]
print(eq02.shape)

(25, 8)

### 3차시 for+if와 비교하기

In [8]:
hot = df[df["온도_섭씨"] > 305]
print(len(hot))

13

## 5단계. 조건 검색 — 불합격만 찾기

In [9]:
fail = df[df["합격여부"] == -1]
print(fail.shape)

(13, 8)

### 고온 기록과 불합격 기록은 같은 기록일까

In [10]:
hot_fail = hot[hot["합격여부"] == -1]
print(len(hot_fail))

3

## 6단계. 정렬하기

In [11]:
df.sort_values("온도_섭씨", ascending=False).head(5)

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
30  2024-03-11 18:00  LOT-0324  EQ-03  포토  310.1  1010.0     51.55     1
15  2024-03-06 16:00  LOT-0089  EQ-03  증착  308.6  1006.8     51.56     1
57  2024-03-20 03:00  LOT-0159  EQ-01  증착  308.4  1014.4     51.59     1
40  2024-03-13 15:00  LOT-0174  EQ-04  증착  308.4  1008.8     49.92     1
11  2024-03-05 12:00  LOT-0192  EQ-04  증착  308.2  1033.0     52.46    -1

## 7단계. loc 맛보기 — 행 이름과 열 이름으로 값 꺼내기

In [12]:
print(df.loc[0, "온도_섭씨"])

297.6

### 조건과 열 이름을 함께 넣기

In [13]:
eq02_view = df.loc[df["설비번호"] == "EQ-02", ["로트번호", "온도_섭씨", "합격여부"]]
print(eq02_view.head())

        로트번호  온도_섭씨  합격여부
0   LOT-0141  297.6     1
2   LOT-0156  296.9    -1
3   LOT-0224  297.2     1
8   LOT-0054  294.4     1
14  LOT-0375  303.4     1

### 구경만 — iloc

In [14]:
print(df.iloc[0:3])

               측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
0  2024-03-01 21:00  LOT-0141  EQ-02  산화  297.6  1005.8     50.02     1
1  2024-03-02 04:00  LOT-0122  EQ-04  식각  300.4  1010.5     49.22     1
2  2024-03-02 08:00  LOT-0156  EQ-02  세정  296.9  1007.6     50.91    -1

## 8단계. 종합 — EQ-02 불합격률 구하기

In [15]:
eq02_fail = eq02[eq02["합격여부"] == -1]
fail_rate = len(eq02_fail) / len(eq02) * 100

print(f"EQ-02 불합격 건수: {len(eq02_fail)}건")
print(f"EQ-02 불합격률: {fail_rate:.1f}%")

EQ-02 불합격 건수: 5건
EQ-02 불합격률: 20.0%

### 여러 열 함께 보기 — 불합격 5건은 어떤 기록일까

In [16]:
print(eq02_fail[["로트번호", "공정명", "온도_섭씨"]])

        로트번호 공정명  온도_섭씨
2   LOT-0156  세정  296.9
21  LOT-0074  식각  299.3
44  LOT-0218  식각  304.9
84  LOT-0217  증착  301.4
85  LOT-0162  세정  307.8

### 직접 해보기 — EQ-04 불합격률

In [17]:
eq04 = df[df["설비번호"] == "EQ-04"]
eq04_fail = eq04[eq04["합격여부"] == -1]
eq04_rate = len(eq04_fail) / len(eq04) * 100

print(f"EQ-04 불합격 건수: {len(eq04_fail)}건")
print(f"EQ-04 불합격률: {eq04_rate:.1f}%")

EQ-04 불합격 건수: 5건
EQ-04 불합격률: 22.7%

### 도전 문제 1 — EQ-02가 아닌 설비 모아 보기 (빠른 학습자용)

In [18]:
others = df[df["설비번호"] != "EQ-02"]
others_fail = others[others["합격여부"] == -1]
others_rate = len(others_fail) / len(others) * 100

print(f"EQ-02 외 {len(others)}건 중 불합격 {len(others_fail)}건 ({others_rate:.1f}%)")

EQ-02 외 75건 중 불합격 8건 (10.7%)

### 도전 문제 2 — 온도가 가장 낮은 5건 (빠른 학습자용)

In [19]:
low5 = df.sort_values("온도_섭씨").head(5)
print(low5[["설비번호", "온도_섭씨", "합격여부"]])

     설비번호  온도_섭씨  합격여부
74  EQ-01  287.0     1
73  EQ-01  291.0     1
67  EQ-01  292.0     1
76  EQ-01  292.4     1
38  EQ-01  292.9     1

## 9단계. AI에게 질문하며 더 알아보기
질문 예시는 강의 "AI로 한 걸음 더" 절에 있습니다. 답은 학생마다 다릅니다.

## 10단계. AI에게 코드 생성 요청하고 직접 실행해보기
강의의 "AI가 만들어줄 수 있는 코드 예시"입니다.

In [20]:
summary = pd.crosstab(df["설비번호"], df["합격여부"])
print(summary)

합격여부   -1   1
설비번호
EQ-01   2  29
EQ-02   5  20
EQ-03   1  21
EQ-04   5  17

## 11단계. 연습문제 — 세정 공정만 골라 살펴보기

In [21]:
cleaning = df[df["공정명"] == "세정"]
print(cleaning.shape)

(18, 8)

In [22]:
cleaning_fail = cleaning[cleaning["합격여부"] == -1]
cleaning_rate = len(cleaning_fail) / len(cleaning) * 100
print(f"세정 {len(cleaning)}건 중 불합격 {len(cleaning_fail)}건 ({cleaning_rate:.1f}%)")

세정 18건 중 불합격 3건 (16.7%)

## 12단계. AI로 재미있는 미니 프로그램 만들기 — 나만의 설비 검색기
강의 예시 코드입니다. 자동 실행을 위해 `input()` 대신 예시 입력값을 넣었습니다.

In [23]:
target = "EQ-02"  # 실제로는 input("검색할 설비번호를 입력하세요: ")

matched = df[df["설비번호"] == target]
if len(matched) > 0:
    matched_fail = matched[matched["합격여부"] == -1]
    rate = len(matched_fail) / len(matched) * 100
    print(f"[{target}] 기록 {len(matched)}건, 불합격 {len(matched_fail)}건 ({rate:.1f}%)")
else:
    print(f"{target} 설비 기록을 찾을 수 없습니다.")

[EQ-02] 기록 25건, 불합격 5건 (20.0%)