# 4차시 — Pandas 가장 기본적인 부분

## 1단계. 데이터 읽기

In [1]:
# pandas를 불러오고, 오늘 실습 CSV 파일을 읽어 df라는 표(DataFrame)에 저장합니다.
# 실행하면 표의 맨 앞 5행이 보입니다 — 열 이름 8개와 값의 모양을 먼저 훑어보세요.
import pandas as pd

# pd.read_csv("파일 경로"): CSV 파일을 읽어 DataFrame(행·열로 된 표)으로 만듭니다.
# df.head(): 표의 앞부분 5행만 보여줍니다.
df = pd.read_csv("../../data/weekly/week04/week04_process_filtering.csv")
df.head()

               측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
0  2024-03-01 21:00  LOT-0141  EQ-02  산화  297.6  1005.8     50.02     1
1  2024-03-02 04:00  LOT-0122  EQ-04  식각  300.4  1010.5     49.22     1
2  2024-03-02 08:00  LOT-0156  EQ-02  세정  296.9  1007.6     50.91    -1
3  2024-03-02 12:00  LOT-0224  EQ-02  산화  297.2  1019.1     47.75     1
4  2024-03-02 21:00  LOT-0302  EQ-01  세정  296.7  1016.9     51.17     1

## 2단계. 기본 정보 확인하기

In [2]:
# 표의 크기(행 개수, 열 개수)를 확인합니다.
# 실행하면 괄호 안에 숫자 두 개가 나옵니다 — 앞이 행 개수, 뒤가 열 개수입니다.
# 크기 정보는 함수가 아니라 표가 가진 속성이라 뒤에 괄호 ()를 붙이지 않습니다.
print(df.shape)     # (행 개수, 열 개수)

(100, 8)

In [3]:
# 표에 들어 있는 열 이름 목록을 확인합니다.
# 실행하면 Index([...]) 안에 열 이름 8개가 나옵니다 — 뒤에서 열을 고를 때 이 이름을 글자 그대로 씁니다.
print(df.columns)   # 열 이름 목록

Index(['측정시간', '로트번호', '설비번호', '공정명', '온도_섭씨', '압력_Pa', '가스유량_slm', '합격여부'], dtype='object')

### 따라 해보기 — 아주 작은 표로 오늘 배울 것 미리 보기
오늘 배울 "열 선택 → 조건 검색 → 정렬 → loc/iloc"을 100행짜리 반도체 데이터로 연습하기 전에,
학생 4명짜리 작은 표로 먼저 감을 잡습니다(강의 자료 "먼저 아주 작은 표로 오늘 배울 것 미리 보기").
지금 다 이해할 필요는 없습니다 — 결과만 눈으로 훑어보고, 각각의 의미는 뒤 단계에서 반도체 데이터로 자세히 배웁니다.

In [4]:
# 딕셔너리로 학생 4명짜리 작은 표를 직접 만들어 toy에 저장하고 출력합니다.
# 실행하면 이름·점수·합격여부 3개 열과 0~3번 행이 있는 표가 보입니다.
# pd.DataFrame({열 이름: [값 목록], ...}): 딕셔너리의 키가 열 이름, 리스트가 그 열의 값이 됩니다.
toy = pd.DataFrame({
    "이름": ["지민", "하은", "서준", "예린"],
    "점수": [90, 72, 88, 65],
    "합격여부": [1, -1, 1, -1],
})
print(toy)

   이름  점수  합격여부
0  지민  90     1
1  하은  72    -1
2  서준  88     1
3  예린  65    -1

아래 다섯 셀은 강의 자료의 "오늘 배울 것 미리 맛보기" 다섯 줄입니다. 하나씩 실행하며 결과를 확인해 보세요.

In [5]:
# 미리 맛보기 1 — 열 선택: 점수 열 하나만 꺼냅니다.
# 실행하면 점수 4개가 왼쪽 행 번호(0~3)와 함께 세로로 나옵니다.
toy["점수"]

0    90
1    72
2    88
3    65
Name: 점수, dtype: int64

In [6]:
# 미리 맛보기 2 — 조건 검색: 점수가 80 이상인 행만 남깁니다.
# 실행하면 점수가 80 이상인 두 사람(지민, 서준)의 행만 보입니다.
toy[toy["점수"] >= 80]

   이름  점수  합격여부
0  지민  90     1
2  서준  88     1

In [7]:
# 미리 맛보기 3 — 정렬: 점수가 높은 사람부터 행을 다시 늘어놓습니다.
# 실행하면 90 → 88 → 72 → 65 순서로 보입니다. 왼쪽 행 번호는 원래 번호를 그대로 따라갑니다.
toy.sort_values("점수", ascending=False)

   이름  점수  합격여부
0  지민  90     1
2  서준  88     1
1  하은  72    -1
3  예린  65    -1

In [8]:
# 미리 맛보기 4 — loc: 합격여부가 1인 행만 고르면서, 이름·점수 두 열만 함께 지정합니다.
# 실행하면 합격한 두 사람(지민, 서준)의 이름과 점수만 보입니다.
toy.loc[toy["합격여부"]==1, ["이름","점수"]]

   이름  점수
0  지민  90
2  서준  88

In [9]:
# 미리 맛보기 5 — iloc: 앞에서부터 위치 0, 1인 두 행만 잘라냅니다.
# 실행하면 지민, 하은 두 행이 보입니다 — 끝 번호 2(서준)는 포함되지 않습니다.
toy.iloc[0:2]

   이름  점수  합격여부
0  지민  90     1
1  하은  72    -1

## 3단계. 열 선택하기

In [10]:
# 온도_섭씨 열 하나만 골라 출력합니다. 열 하나를 고르면 Series(이름표가 붙은 한 줄짜리 데이터)가 됩니다.
# 실행하면 값이 너무 많아 앞 5개·뒤 5개만 보이고, 맨 아래에 Name: 온도_섭씨, Length: 100이 나옵니다.
print(df["온도_섭씨"])                 # 열 하나 (Series)

0     297.6
1     300.4
2     296.9
3     297.2
4     296.7
      ...
95    305.9
96    302.2
97    297.6
98    297.4
99    300.9
Name: 온도_섭씨, Length: 100, dtype: float64

In [11]:
# 온도_섭씨와 압력_Pa 두 열을 함께 골라 출력합니다. 열 이름 두 개를 리스트 [ ]로 묶어서 넣습니다.
# 실행하면 두 열짜리 표가 보이고, 맨 아래에 [100 rows x 2 columns]가 나옵니다.
print(df[["온도_섭씨", "압력_Pa"]])      # 열 여러 개 (대괄호 두 번!)

    온도_섭씨   압력_Pa
0   297.6  1005.8
1   300.4  1010.5
2   296.9  1007.6
3   297.2  1019.1
4   296.7  1016.9
..    ...     ...
95  305.9  1005.4
96  302.2  1009.8
97  297.6  1029.9
98  297.4  1028.7
99  300.9  1004.8

[100 rows x 2 columns]

In [12]:
# [가장 흔한 함정] 여러 열을 고를 때 대괄호를 한 번만 쓰면 오류가 납니다. 이 셀은 실행해도 아무것도 나오지 않습니다.
# 아래 줄 맨 앞의 #을 지우고 실행하면 KeyError가 나는 것을 직접 볼 수 있습니다.
# 확인한 뒤에는 다시 #을 붙여 두세요(노트북을 처음부터 다시 실행할 때 여기서 멈추지 않도록).
# print(df["온도_섭씨", "압력_Pa"])

## 4단계. 조건 검색 — 특정 설비만 찾기

In [13]:
# 설비번호가 EQ-02인 행만 골라 eq02라는 새 표에 저장합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 행이 100개에서 얼마나 줄었는지 확인해 보세요.
# 안쪽 조건식이 행마다 True/False를 만들고, 바깥 df[ ]가 True인 행만 남깁니다(조건 검색).
eq02 = df[df["설비번호"] == "EQ-02"]
print(eq02.shape)

(25, 8)

## 5단계. 조건 검색 — 불합격 데이터만 찾기

In [14]:
# 합격여부가 -1(불합격)인 행만 골라 fail이라는 새 표에 저장합니다.
# 실행하면 (불합격 행 개수, 열 개수)가 출력됩니다. 결과는 새 표이고, 원본 df는 그대로입니다.
fail = df[df["합격여부"] == -1]
print(fail.shape)

(13, 8)

## 6단계. 정렬

In [15]:
# 온도_섭씨가 높은 순서(내림차순)로 표 전체를 정렬한 뒤 앞의 5행만 봅니다.
# 실행하면 온도가 가장 높은 5건이 표로 보입니다 — 맨 윗줄 온도가 가장 높은 값인지 확인해 보세요.
# sort_values("열 이름"): 그 열을 기준으로 정렬합니다. ascending을 생략하면 작은 값부터(오름차순) 나옵니다.
df.sort_values("온도_섭씨", ascending=False).head(5)

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
30  2024-03-11 18:00  LOT-0324  EQ-03  포토  310.1  1010.0     51.55     1
15  2024-03-06 16:00  LOT-0089  EQ-03  증착  308.6  1006.8     51.56     1
57  2024-03-20 03:00  LOT-0159  EQ-01  증착  308.4  1014.4     51.59     1
40  2024-03-13 15:00  LOT-0174  EQ-04  증착  308.4  1008.8     49.92     1
11  2024-03-05 12:00  LOT-0192  EQ-04  증착  308.2  1033.0     52.46    -1

## 7단계(종합). EQ-02 불합격률 계산하기

In [16]:
# 4단계에서 만든 eq02 표에서 불합격(-1)만 다시 골라내고, 불합격률(%)을 계산해 출력합니다.
# 실행하면 EQ-02의 불합격 건수와 불합격률 두 줄이 나옵니다. 불합격률 = 불합격 행 개수 ÷ EQ-02 전체 행 개수 × 100
# {fail_rate:.1f}는 소수점 아래 한 자리까지만 보여 달라는 f-string 표기입니다.
eq02_fail = eq02[eq02["합격여부"] == -1]
fail_rate = len(eq02_fail) / len(eq02) * 100

print(f"EQ-02 불합격 건수: {len(eq02_fail)}건")
print(f"EQ-02 불합격률: {fail_rate:.1f}%")

EQ-02 불합격 건수: 5건
EQ-02 불합격률: 20.0%

## 8단계. 오늘의 학습을 한 문장으로 정리하기

> Pandas의 조건 검색은 반복문으로 하나씩 확인하던 일을 한 줄로 처리해준다.

### 도전 문제 1 — EQ-02가 아닌 설비의 불합격률 (빠른 학습자용)
강의 자료 "도전 실습" 절의 도전 문제 1입니다. 위 8단계 문장을 먼저 쓰고, 시간이 남으면 도전 문제 1~4를 풀어 보세요.
EQ-02가 아닌 나머지 설비의 기록만 골라내고, 그 안에서 불합격 비율을 계산해 EQ-02(20.0%)와 비교합니다.

In [17]:
# [도전 1-1] 설비번호가 EQ-02가 아닌 행만 골라 others라는 새 표에 저장합니다.
# 실행하면 (행 개수, 열 개수)가 출력됩니다 — 전체 100행에서 EQ-02 25행을 뺀 개수인지 확인해 보세요.
others = df[df["설비번호"] != "EQ-02"]
print(others.shape)

(75, 8)

> **참고**
>
> - 빈칸: 강의 자료 "도전 실습" 절 **도전 문제 1** 상자의 코드에 그대로 나옵니다. 4단계에서 쓴 "같다" 비교의 반대 뜻을 가진 비교 연산자로, 조건에 맞지 **않는** 행에서 True가 됩니다.
> - 조건식이 True/False 목록을 만들고 True인 행만 남는 원리는 강의 "조건 검색 — 원하는 행만 골라내기" 절의 "동작 원리 — 2단계로 이해하기"를 다시 보세요.
>
> **정답 해설:** 빈칸은 `!=`(같지 않다)입니다. `df["설비번호"] != "EQ-02"`는 EQ-02가 아닌 행에서 True가 되므로 EQ-01·EQ-03·EQ-04 기록만 남습니다.

In [18]:
# [도전 1-2] others 표에서 불합격(-1)만 다시 골라내고, 나머지 설비의 불합격 건수와 불합격률(%)을 출력합니다.
# 실행하면 두 줄이 나옵니다 — 7단계에서 EQ-02 불합격률을 구한 방법과 같습니다.
others_fail = others[others["합격여부"] == -1]
others_rate = len(others_fail) / len(others) * 100

print(f"EQ-02 외 불합격 건수: {len(others_fail)}건")
print(f"EQ-02 외 불합격률: {others_rate:.1f}%")

EQ-02 외 불합격 건수: 8건
EQ-02 외 불합격률: 10.7%

> **참고**
>
> - 두 빈칸 모두 강의 자료 "종합 — 3차시 함수와 Pandas 비교하기" 절의 코드(EQ-02 불합격률 계산)에 그대로 나옵니다.
> - 첫 번째 빈칸: `불합격 수 / 전체 수`는 0~1 사이 비율이라, 퍼센트 값으로 바꾸는 곱셈을 붙입니다.
> - 두 번째 빈칸: f-string의 `{변수}` 안에서 변수 이름 뒤에 붙여 소수점 아래 자릿수를 정하는 표기입니다.
>
> **정답 해설:** 첫 번째 빈칸은 `* 100`, 두 번째 빈칸은 `:.1f`입니다. 7단계의 `fail_rate` 계산과 같은 식을 others 표에 적용한 것입니다.

In [19]:
# [도전 1-3] 7단계에서 구한 EQ-02 불합격률(fail_rate)과 방금 구한 나머지 설비 불합격률(others_rate)을 한 줄에 나란히 출력합니다.
# 실행하면 두 비율이 함께 보입니다 — 어느 쪽이 더 높은지 한 문장으로 말해 보세요.
print(f"EQ-02: {fail_rate:.1f}% / 나머지 설비: {others_rate:.1f}%")

EQ-02: 20.0% / 나머지 설비: 10.7%

### 도전 문제 2 — 온도 하위 5건 확인하기 (빠른 학습자용)
강의 자료 "도전 실습" 절의 도전 문제 2입니다. 온도를 오름차순으로 정렬해 온도가 가장 낮았던 하위 5건을 보고,
그 5건 중 불합격이 몇 건인지 셉니다.

In [20]:
# [도전 2-1] 온도_섭씨가 낮은 순서(오름차순)로 정렬한 뒤 앞의 5행을 low5에 저장하고 표로 봅니다.
# 실행하면 온도가 가장 낮은 5건이 보입니다 — 맨 윗줄 온도가 가장 낮은 값인지 확인해 보세요.
# ascending을 생략했으므로 작은 값부터(오름차순) 정렬됩니다.
low5 = df.sort_values("온도_섭씨").head(5)
low5

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
74  2024-03-24 00:00  LOT-0153  EQ-01  세정  287.0  1006.2     54.86     1
73  2024-03-23 20:00  LOT-0268  EQ-01  세정  291.0  1001.6     51.49     1
67  2024-03-22 19:00  LOT-0365  EQ-01  세정  292.0  1008.4     53.88     1
76  2024-03-24 08:00  LOT-0340  EQ-01  증착  292.4  1013.6     49.11     1
38  2024-03-13 07:00  LOT-0392  EQ-01  포토  292.9  1014.3     46.45     1

> **참고**
>
> - 빈칸: 강의 자료 "정렬 — 값이 높은/낮은 순서로 보기" 절의 코드와 "도전 실습" 절 도전 문제 2 상자에 나오는 메서드입니다. 지정한 열의 값 크기 순서대로 행을 다시 늘어놓습니다.
> - 같은 절의 "주의 — 기본값은 오름차순"처럼, `ascending`을 생략하면 작은 값이 먼저 나옵니다.
>
> **정답 해설:** 빈칸은 `sort_values`입니다. `ascending=False`를 쓰지 않았으므로 오름차순으로 정렬되고, `head(5)`가 가장 낮은 5건을 남깁니다.

In [21]:
# [도전 2-2] low5에서 불합격(-1)인 행만 골라 low5_fail에 저장하고, 몇 건인지 출력합니다.
# 실행하면 온도 하위 5건 중 불합격 건수가 한 줄로 나옵니다.
low5_fail = low5[low5["합격여부"] == -1]
print(f"온도 하위 5건 중 불합격: {len(low5_fail)}건")

온도 하위 5건 중 불합격: 0건

> **참고**
>
> - 빈칸: 강의 자료 "조건 검색 — 원하는 행만 골라내기" 절의 불합격 데이터 찾기 코드에 나오는 비교 연산자입니다. 3차시에서 배운 것처럼 `=`(저장)과는 다른, 값이 같은지 묻는 연산자입니다.
>
> **정답 해설:** 빈칸은 `==`입니다. `low5["합격여부"] == -1`이 불합격 행에서만 True가 됩니다.

### 도전 문제 3 — loc으로 EQ-02 불합격 로트 뽑기 (빠른 학습자용)
강의 자료 "도전 실습" 절의 도전 문제 3입니다. EQ-02이면서 불합격한 행만 고르고, 로트번호·온도_섭씨 두 열만 함께 뽑습니다.

In [22]:
# [도전 3] 설비번호가 EQ-02이고 합격여부가 -1(불합격)인 행만 고르면서, 로트번호·온도_섭씨 두 열만 함께 지정해 출력합니다.
# 실행하면 EQ-02에서 불합격한 로트의 로트번호와 온도가 표로 나옵니다 — 행 개수가 7단계 불합격 건수와 같은지 세어 보세요.
# 두 조건을 동시에 적용할 때는 조건마다 괄호 ( )로 감싸야 하고, 파이썬의 and는 쓸 수 없습니다.
eq02_fail_view = df.loc[(df["설비번호"]=="EQ-02") & (df["합격여부"]==-1), ["로트번호", "온도_섭씨"]]
print(eq02_fail_view)

        로트번호  온도_섭씨
2   LOT-0156  296.9
21  LOT-0074  299.3
44  LOT-0218  304.9
84  LOT-0217  301.4
85  LOT-0162  307.8

> **참고**
>
> - 첫 번째 빈칸: 강의 자료 "loc / iloc — 이름과 위치로 정확히 접근하기" 절의 "동작 원리"에 나오는 `df.(인덱서)[행조건, 열이름목록]` 형태입니다. 조건으로 행을 고르면서 열 이름도 함께 받는 쪽을 고르세요("언제 무엇을 쓸까?"의 첫 줄).
> - 두 번째 빈칸: 강의 자료 "도전 실습" 절 도전 문제 3 상자와 "과제(다음 차시까지)" 절의 체크포인트에 나오는 기호로, 두 True/False 목록을 "그리고"로 묶어 둘 다 True인 행만 남깁니다.
>
> **정답 해설:** 첫 번째 빈칸은 `loc`, 두 번째 빈칸은 `&`입니다. iloc은 정수 위치만 받으므로 조건식을 넣을 수 없고, True/False 목록(Series)끼리는 `and` 대신 `&`로 묶어야 합니다.

### 도전 문제 4 — iloc으로 마지막 5행 비교하기 (빠른 학습자용)
강의 자료 "도전 실습" 절의 도전 문제 4입니다. 원본 순서의 마지막 5행과, 온도로 정렬한 뒤의 마지막 5행을 비교해
두 결과가 왜 다른지(원본 순서 vs 정렬된 순서) 설명해 봅니다.

In [23]:
# [도전 4-1] 원본 df에서 위치 기준으로 마지막 5행을 잘라 봅니다. 음수 위치는 뒤에서부터 셉니다.
# 실행하면 맨 끝 5행(행 번호 95~99)이 표로 보입니다 — 측정시간이 가장 늦은 기록들입니다.
df.iloc[-5:]

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
95  2024-04-01 00:00  LOT-0208  EQ-03  증착  305.9  1005.4     52.23     1
96  2024-04-02 01:00  LOT-0224  EQ-03  세정  302.2  1009.8     52.95     1
97  2024-04-02 03:00  LOT-0248  EQ-03  증착  297.6  1029.9     49.09     1
98  2024-04-02 13:00  LOT-0005  EQ-01  증착  297.4  1028.7     50.68     1
99  2024-04-02 22:00  LOT-0179  EQ-03  증착  300.9  1004.8     46.42     1

> **참고**
>
> - 빈칸: 강의 자료 "도전 실습" 절 도전 문제 4 상자의 코드에 그대로 나옵니다.
> - 강의 "loc / iloc" 절 iloc 코드의 "맨 마지막 행"(음수 위치 `-1`)과, "앞에서 3개 행"의 슬라이스(`시작:끝`) 표기를 합친 모양입니다. 끝 번호를 비워 두면 "끝까지"라는 뜻입니다(과제 3의 `:5`는 반대로 시작 번호를 비운 예).
>
> **정답 해설:** 빈칸은 `-5:`입니다. 뒤에서 5번째 위치부터 끝까지, 즉 마지막 5행입니다.

In [24]:
# [도전 4-2] 온도_섭씨 오름차순으로 정렬한 표에서, 다시 위치 기준으로 마지막 5행을 잘라 봅니다.
# 실행하면 온도가 가장 높은 5건이 보입니다 — 4-1 결과와 왼쪽 행 번호·값이 어떻게 다른지 비교해 보세요.
df.sort_values("온도_섭씨").iloc[-5:]

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
11  2024-03-05 12:00  LOT-0192  EQ-04  증착  308.2  1033.0     52.46    -1
57  2024-03-20 03:00  LOT-0159  EQ-01  증착  308.4  1014.4     51.59     1
40  2024-03-13 15:00  LOT-0174  EQ-04  증착  308.4  1008.8     49.92     1
15  2024-03-06 16:00  LOT-0089  EQ-03  증착  308.6  1006.8     51.56     1
30  2024-03-11 18:00  LOT-0324  EQ-03  포토  310.1  1010.0     51.55     1

> **참고**
>
> - 빈칸: 강의 자료 "loc / iloc — 이름과 위치로 정확히 접근하기" 절에서 "위치(정수)로 찾기"에 쓰는 쪽입니다. "언제 무엇을 쓸까?"의 "'처음 5행', '마지막 3행'처럼 순서(위치)로 잘라내고 싶다" 줄을 다시 보세요.
> - 정렬한 뒤에 위치로 자르면 "지금 표에 놓인 순서"의 마지막 5행이 나옵니다.
>
> **정답 해설:** 빈칸은 `iloc`입니다. 정렬된 표에서 위치 기준 마지막 5행 = 온도 상위 5건이라, 원본 순서의 마지막 5행(4-1)과 다릅니다.

In [25]:
# [도전 4-3] 이번에는 측정시간 순서로 정렬한 뒤 마지막 5행을 봅니다.
# 실행하면 4-1(원본의 마지막 5행)과 같은 결과가 나옵니다 — 이 데이터가 처음부터 측정시간 순서로 저장돼 있기 때문입니다.
df.sort_values("측정시간").iloc[-5:]

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
95  2024-04-01 00:00  LOT-0208  EQ-03  증착  305.9  1005.4     52.23     1
96  2024-04-02 01:00  LOT-0224  EQ-03  세정  302.2  1009.8     52.95     1
97  2024-04-02 03:00  LOT-0248  EQ-03  증착  297.6  1029.9     49.09     1
98  2024-04-02 13:00  LOT-0005  EQ-01  증착  297.4  1028.7     50.68     1
99  2024-04-02 22:00  LOT-0179  EQ-03  증착  300.9  1004.8     46.42     1

**설명 예시**: `df.iloc[-5:]`는 원래 저장된 순서(측정시간 순)의 마지막 5행이고, `df.sort_values("온도_섭씨").iloc[-5:]`는 온도로 줄을 다시 세운 뒤의 마지막 5행(온도 상위 5건)이라 결과가 다르다. iloc은 "지금 표에 놓인 순서"의 위치로 자른다.

## 9단계. AI에게 질문하며 더 알아보기
오늘 배운 Pandas 기본기에 대해 AI 챗봇에게 질문해 이해를 넓혀봅니다.

질문 예시:
- "pandas의 loc과 iloc은 정확히 언제 다르게 동작하나요?"
- "df[df['열']==값] 조건 검색과 df.query()는 어떻게 다른가요?"
- "Pandas의 Series와 DataFrame은 정확히 어떻게 다른가요?"
- "df.sort_values()에서 여러 열을 동시에 기준으로 정렬하려면 어떻게 하나요?"

## 10단계. AI에게 코드 생성 요청하고 직접 실행해보기
프롬프트 예시: "설비번호와 합격여부 열이 있는 DataFrame에서, 설비별 합격/불합격 건수를 한 번에
표로 만들어주는 코드를 만들어줘."

아래는 AI가 생성해줄 수 있는 예시 코드와 실행 결과입니다.

**주의**: AI가 만든 코드가 `df = pd.DataFrame(...)`처럼 `df`라는 이름에 새 표를 저장하면 1단계에서 읽은 100행 데이터가 덮어써져 11·12단계에서 `KeyError: '온도_섭씨'`가 납니다. 강의 자료의 예시 코드처럼 `sample_df` 같은 다른 이름으로 바꿔 실행하세요. 이미 덮어썼다면 1단계 셀을 다시 실행하면 됩니다.

In [26]:
# AI가 만들어 줄 수 있는 예시 코드입니다(강의 자료와 같음). 5행짜리 작은 표를 sample_df라는 새 이름으로 만들어 설비별 합격/불합격 건수를 셉니다.
# 실행하면 설비번호(행) × 합격여부(열) 건수 표가 나옵니다. 이름을 df가 아닌 sample_df로 지었기 때문에 1단계에서 읽은 df(100행)는 그대로 남습니다.
# pd.crosstab(행으로 쓸 열, 칸으로 쓸 열): 두 열의 값 조합마다 건수를 세어 표로 만듭니다(오늘 배우지 않은 함수, 7차시 groupby와 연결).
import pandas as pd

data = {
    "설비번호": ["EQ-01", "EQ-01", "EQ-02", "EQ-02", "EQ-02"],
    "합격여부": [1, -1, 1, 1, -1],
}
sample_df = pd.DataFrame(data)

summary = pd.crosstab(sample_df["설비번호"], sample_df["합격여부"])
print(summary)

합격여부   -1   1
설비번호
EQ-01   1   1
EQ-02   1   2

In [27]:
# 같은 crosstab 코드를 실제 공정 데이터 df(100행)에 적용해 설비별 합격/불합격 건수를 셉니다.
# 실행하면 EQ-01~EQ-04 네 설비의 -1(불합격)·1(합격) 건수 표가 나옵니다 — EQ-02의 -1 칸이 7단계 불합격 건수와 같은지 확인해 보세요.
summary = pd.crosstab(df["설비번호"], df["합격여부"])
print(summary)

합격여부   -1   1
설비번호
EQ-01   2  29
EQ-02   5  20
EQ-03   1  21
EQ-04   5  17

## 11단계. 연습문제 — loc/iloc으로 원하는 데이터 골라내기
> `loc`은 끝 번호를 포함하고, `iloc`은 끝 번호를 포함하지 않는다는 점을 기억합니다.

### 따라 해보기 1 — loc: 이름(라벨)으로 찾기
강의 자료 "loc / iloc" 절의 코드입니다. `loc`은 행 인덱스 값과 열 이름을 그대로 씁니다.

In [28]:
# loc으로 0번 행의 온도_섭씨 값 하나만 꺼냅니다(이름(라벨)으로 찾기).
# 실행하면 숫자 하나가 출력됩니다 — 1단계 df.head()의 첫 행 온도와 같은지 확인해 보세요.
# df.loc[행 이름, 열 이름]: 대괄호 안을 쉼표로 나눠 앞은 행, 뒤는 열을 지정합니다.
# 행 하나 + 열 하나
print(df.loc[0, "온도_섭씨"])

297.6

In [29]:
# loc으로 설비번호가 EQ-02인 행만 고르면서, 로트번호·온도_섭씨·합격여부 세 열만 함께 지정합니다.
# 실행하면 EQ-02 행 중 앞 5행이 세 열짜리 표로 보입니다 — 왼쪽 행 번호(0, 2, 3, ...)는 원래 df의 번호입니다.
# 조건으로 행을 고르면서, 보고 싶은 열도 함께 지정
eq02_view = df.loc[df["설비번호"] == "EQ-02", ["로트번호", "온도_섭씨", "합격여부"]]
print(eq02_view.head())

        로트번호  온도_섭씨  합격여부
0   LOT-0141  297.6     1
2   LOT-0156  296.9    -1
3   LOT-0224  297.2     1
8   LOT-0054  294.4     1
14  LOT-0375  303.4     1

### 따라 해보기 2 — iloc: 위치(정수)로 찾기
`iloc`은 앞에서부터 0, 1, 2, ...로 센 위치 번호만 받습니다. 열 이름을 넣으면 `ValueError`가 납니다.

In [30]:
# iloc으로 위치 0(맨 첫 번째) 행 전체를 꺼냅니다(위치(정수)로 찾기).
# 실행하면 첫 행의 8개 열 값이 세로로 나옵니다 — 행 하나를 꺼내면 Series가 됩니다.
# df.iloc[위치]: 앞에서부터 0, 1, 2, ...로 센 순서 번호로 고릅니다(2차시 리스트 인덱스와 같은 방식).
# 첫 번째 행 (위치 0)
print(df.iloc[0])

측정시간        2024-03-01 21:00
로트번호                LOT-0141
설비번호                   EQ-02
공정명                       산화
온도_섭씨                  297.6
압력_Pa                 1005.8
가스유량_slm               50.02
합격여부                       1
Name: 0, dtype: object

In [31]:
# iloc으로 앞에서 3개 행(위치 0, 1, 2)과 앞에서 2개 열(측정시간, 로트번호)만 잘라냅니다.
# 실행하면 3행 × 2열짜리 작은 표가 나옵니다 — iloc 슬라이스는 끝 번호(3, 2)를 포함하지 않습니다.
# 앞에서 3개 행, 앞에서 2개 열
print(df.iloc[0:3, 0:2])

               측정시간      로트번호
0  2024-03-01 21:00  LOT-0141
1  2024-03-02 04:00  LOT-0122
2  2024-03-02 08:00  LOT-0156

In [32]:
# iloc에 -1을 넣어 맨 마지막 행을 꺼냅니다. 음수 위치는 뒤에서부터 셉니다.
# 실행하면 마지막 행의 8개 열 값이 세로로 나옵니다.
# 맨 마지막 행
print(df.iloc[-1])

측정시간        2024-04-02 22:00
로트번호                LOT-0179
설비번호                   EQ-03
공정명                       증착
온도_섭씨                  300.9
압력_Pa                 1004.8
가스유량_slm               46.42
합격여부                       1
Name: 99, dtype: object

### 직접 풀어보기 — 연습문제
강의 자료 "연습문제 — loc/iloc으로 원하는 데이터 골라내기" 절의 정답 코드입니다.

In [33]:
# 연습 1: loc으로 0~4번 행의 온도_섭씨, 압력_Pa 두 열만 골라 subset_loc에 저장하고 출력합니다.
# 실행하면 두 열짜리 표가 나옵니다 — 행이 몇 개 나오는지 세어 보세요(loc은 끝 번호를 포함합니다).
subset_loc = df.loc[0:4, ["온도_섭씨", "압력_Pa"]]
print(subset_loc)

   온도_섭씨   압력_Pa
0  297.6  1005.8
1  300.4  1010.5
2  296.9  1007.6
3  297.2  1019.1
4  296.7  1016.9

In [34]:
# 연습 2: iloc으로 첫 번째 행 전체를 골라 first_row에 저장하고 출력합니다.
# 실행하면 첫 행의 8개 열 값이 세로로(Series) 나옵니다.
first_row = df.iloc[0]
print(first_row)

측정시간        2024-03-01 21:00
로트번호                LOT-0141
설비번호                   EQ-02
공정명                       산화
온도_섭씨                  297.6
압력_Pa                 1005.8
가스유량_slm               50.02
합격여부                       1
Name: 0, dtype: object

## 12단계. AI로 재미있는 미니 프로그램 만들기 🎉 — 나만의 설비 검색기
프롬프트 예시: "설비번호 열이 있는 DataFrame df에서, 사용자가 input()으로 설비번호(예: EQ-02)를
입력하면 그 설비의 기록 건수와 평균 온도를 보기 좋게 출력하는 파이썬 코드를 만들어줘."

In [35]:
# 검색할 설비번호를 target에 넣고, 그 설비의 기록 건수와 평균 온도를 출력하는 설비 검색기입니다.
# 실행하면 EQ-02 검색 결과 세 줄이 나옵니다. target을 "EQ-99"처럼 없는 설비로 바꿔 다시 실행해 보세요.
# 열.mean()은 그 열의 평균을 구합니다. 자동 실행 검증 때문에 input() 대신 예시 값을 넣었습니다.
target = "EQ-02"  # 실제로는 input("검색할 설비번호를 입력하세요: ")

matched = df[df["설비번호"] == target]
if len(matched) > 0:
    print(f"🔍 {target} 검색 결과")
    print(f"기록 건수: {len(matched)}건")
    print(f"평균 온도: {matched['온도_섭씨'].mean():.1f}도")
else:
    print(f"{target} 설비 기록을 찾을 수 없습니다.")

🔍 EQ-02 검색 결과
기록 건수: 25건
평균 온도: 300.1도