# 4차시 실습 — Pandas 가장 기본적인 부분 (정답)

## 막혔을 때

- 결과가 이상하거나 오류가 계속 나면 메뉴에서 **Kernel → Restart Kernel and Run All Cells…**(옛 화면은 Kernel → Restart & Run All)를 눌러 위에서부터 다시 실행하세요. 학생용은 아직 채우지 않은 **첫 빈칸에서 멈춥니다. 정상입니다.** 그 빈칸을 채우고 그 셀부터 Shift + Enter로 이어 가세요.
- 밑줄로 된 빈칸 표시는 채울 자리만 알려 줍니다. 밑줄 개수와 상관없이 밑줄을 모두 지우고 필요한 만큼(글자 하나든 이름 전체든) 씁니다.
- 셀을 지웠거나 망가뜨렸다면 **Edit → Undo**(셀 바깥을 누른 뒤 `z` 키)로 되돌립니다. 안 되면 실습 키트에서 이 노트북 파일만 다시 꺼내 쓰세요(폴더 구조는 그대로 둡니다).
- 빨간 오류 메시지는 **마지막 줄**부터 읽으세요. 오류 이름(`NameError`, `KeyError` …)과 문제가 된 이름이 거기 있습니다.

## 1단계. CSV 파일 읽기 — read_csv

카페 주문 12건(교육용 가상 데이터)입니다. `pd.read_csv("파일 경로", encoding="utf-8-sig")`로 표를 읽어 `cafe`에 담습니다.

In [1]:
import pandas as pd

cafe = pd.read_csv("../../data/weekly/week04/week04_easy_cafe_orders.csv", encoding="utf-8-sig")
cafe.head()

    주문번호   매장     메뉴   종류  가격_KRW  수량_count  평가
0  C-001  강남점  아메리카노   커피    4500         2   1
1  C-002  홍대점   카페라테   커피    5000         1   1
2  C-003  강남점     녹차    차    4800         1  -1
3  C-004  강남점  치즈케이크  디저트    6500         1  -1
4  C-005  홍대점  아메리카노   커피    4500         3   1

> 찾아보기: "CSV 파일이란" — 강의 자료의 ChatGPT 질문을 써 보세요.

## 2단계. 표의 크기와 열 이름 확인하기 — shape, columns

`shape`는 (행 수, 열 수)입니다. 괄호 `()` 없이 씁니다.

In [2]:
print(cafe.shape)

(12, 7)

In [3]:
print(cafe.columns)

Index(['주문번호', '매장', '메뉴', '종류', '가격_KRW', '수량_count', '평가'], dtype='str')

## 3단계. 열 선택하기

열 하나는 대괄호 한 겹 `cafe["열"]`, 여러 열은 **대괄호 두 겹** `cafe[["열1", "열2"]]`입니다.

In [4]:
print(cafe["가격_KRW"].head())

0    4500
1    5000
2    4800
3    6500
4    4500
Name: 가격_KRW, dtype: int64

In [5]:
print(cafe[["메뉴", "가격_KRW", "평가"]].head())

      메뉴  가격_KRW  평가
0  아메리카노    4500   1
1   카페라테    5000   1
2     녹차    4800  -1
3  치즈케이크    6500  -1
4  아메리카노    4500   1

(구경) `loc`은 행 번호와 열 이름으로 칸 하나를 꺼냅니다. 실행해서 결과만 보세요.

In [6]:
print(cafe.loc[0, "가격_KRW"])

4500

## 4단계. 조건 검색 — 원하는 행만 골라내기

`cafe["종류"] == "커피"`는 행마다 True/False를 만들고, 그것을 다시 `cafe[ ]`에 넣으면 True인 행만 남습니다.

In [7]:
check = cafe["종류"] == "커피"
print(check.head())

0     True
1     True
2    False
3    False
4     True
Name: 종류, dtype: bool

In [8]:
coffee = cafe[cafe["종류"] == "커피"]
print(coffee.shape)

(5, 7)

In [9]:
pricey = cafe[cafe["가격_KRW"] > 5000]
print(len(pricey))

5

> 찾아보기: "pandas 조건 검색" — 강의 자료의 ChatGPT 질문을 써 보세요.

## 5단계. 골라낸 표에서 한 번 더 고르기

고른 표(`pricey`)에서 다시 조건을 걸면 두 조건을 모두 만족하는 행이 남습니다.

`평가`: 1 = 좋아요, -1 = 별로예요(반도체 데이터의 `합격여부` 1 = 합격, -1 = 불합격과 같은 표기).

In [10]:
pricey_bad = pricey[pricey["평가"] == -1]
print(len(pricey_bad))

3

## 6단계. 정렬하기 — sort_values

`ascending=False`는 큰 값부터(내림차순)입니다. 빼면 작은 값부터 정렬합니다.

In [11]:
cafe.sort_values("가격_KRW", ascending=False).head(5)

     주문번호   매장     메뉴   종류  가격_KRW  수량_count  평가
9   C-010  홍대점  초코케이크  디저트    6800         1  -1
3   C-004  강남점  치즈케이크  디저트    6500         1  -1
5   C-006  홍대점  바닐라라테   커피    5500         1  -1
8   C-009  강남점   카페모카   커피    5500         1   1
10  C-011  강남점    유자차    차    5200         1   1

## 7단계. 반도체 데이터로 확인하기 — 공정 기록 100건

공정 기록 100건(교육용 가상 데이터)입니다. 1~5단계와 같은 코드에서 파일 이름·표 이름·열 이름만 바뀝니다. `합격여부`: 1 = 합격, -1 = 불합격.

In [12]:
df = pd.read_csv("../../data/weekly/week04/week04_process_filtering.csv", encoding="utf-8-sig")
print(df.shape)

(100, 8)

In [13]:
print(df.columns)

Index(['측정시간', '로트번호', '설비번호', '공정명', '온도_C', '압력_Pa', '가스유량_slm', '합격여부'], dtype='str')

In [14]:
eq01 = df[df["설비번호"] == "EQ-01"]
eq01_fail = eq01[eq01["합격여부"] == -1]
print(len(eq01), len(eq01_fail))

31 2

In [15]:
fail = df[df["합격여부"] == -1]
print(len(fail) / len(df) * 100)

13.0

## 8단계. 반도체 데이터 실습

7단계 셀을 먼저 실행한 뒤 풀어요. 실습지 문제 1~3과 같은 문제입니다. 오늘의 미션: EQ-02에서 불합격이 몇 건인지 찾아 보고합니다.

### 문제 1 — 설비번호·온도_C·합격여부 세 열만 고르기

In [16]:
small = df[["설비번호", "온도_C", "합격여부"]]
print(small.shape)

(100, 3)

In [17]:
small.head()

    설비번호   온도_C  합격여부
0  EQ-02  297.6     1
1  EQ-04  300.4     1
2  EQ-02  296.9    -1
3  EQ-02  297.2     1
4  EQ-01  296.7     1

### 문제 2 — EQ-02 기록 고르고, 그중 불합격 세기

In [18]:
eq02 = df[df["설비번호"] == "EQ-02"]
eq02_fail = eq02[eq02["합격여부"] == -1]
print(len(eq02), len(eq02_fail))

25 5

In [19]:
eq02_rate = len(eq02_fail) / len(eq02) * 100
print(f"EQ-02 불합격률은 {eq02_rate}%입니다.")

EQ-02 불합격률은 20.0%입니다.

### 문제 3 — 온도가 높은 기록 5건 보기

In [20]:
df.sort_values("온도_C", ascending=False).head(5)

                측정시간      로트번호   설비번호 공정명   온도_C   압력_Pa  가스유량_slm  합격여부
30  2024-03-11 18:00  LOT-0324  EQ-03  포토  310.1  1010.0     51.55     1
15  2024-03-06 16:00  LOT-0089  EQ-03  증착  308.6  1006.8     51.56     1
57  2024-03-20 03:00  LOT-0159  EQ-01  증착  308.4  1014.4     51.59     1
40  2024-03-13 15:00  LOT-0174  EQ-04  증착  308.4  1008.8     49.92     1
11  2024-03-05 12:00  LOT-0192  EQ-04  증착  308.2  1033.0     52.46    -1

> 찾아보기: "불량률 계산 분모" — 강의 자료의 ChatGPT 질문을 써 보세요.

## 9단계. AI로 한 걸음 더

ChatGPT에 이렇게 물어봤습니다.

> pandas 표 df에 "공정명"과 "합격여부"(1 = 합격, -1 = 불합격) 열이 있어. 공정명마다 기록 수와 불합격 건수를 한 줄씩 출력하는 짧은 코드를 만들어 줘. 오늘 배운 조건 검색만 써 줘.

아래는 받은 코드의 예시입니다. `for`는 3차시에 배웠습니다. 실행해서 불합격 건수를 모두 더하면 7단계 전체 불합격 13건(100건 중 13.0%)과 같은지 확인하세요.

In [21]:
for name in ["산화", "포토", "식각", "증착", "세정"]:
    part = df[df["공정명"] == name]
    part_fail = part[part["합격여부"] == -1]
    print(f"{name}: 기록 {len(part)}건, 불합격 {len(part_fail)}건")

산화: 기록 23건, 불합격 1건
포토: 기록 20건, 불합격 3건
식각: 기록 15건, 불합격 2건
증착: 기록 24건, 불합격 4건
세정: 기록 18건, 불합격 3건