# 4차시 실습 — Pandas 가장 기본적인 부분 (정답)

`cafe` = 카페 주문 12행 7열, `df` = 공정 기록 100행 8열(교육용 가상 데이터). `합격여부`: 1 = 합격, -1 = 불합격.

## 1단계. 데이터 읽기

In [1]:
import pandas as pd

cafe = pd.read_csv("../../data/weekly/week04/week04_easy_cafe_orders.csv", encoding="utf-8-sig")
cafe.head()

    주문번호   매장     메뉴   종류  가격_원  수량_개  평가
0  C-001  강남점  아메리카노   커피  4500     2   1
1  C-002  홍대점   카페라테   커피  5000     1   1
2  C-003  강남점     녹차    차  4800     1  -1
3  C-004  강남점  치즈케이크  디저트  6500     1  -1
4  C-005  홍대점  아메리카노   커피  4500     3   1

## 2단계. 표의 크기와 열 이름 확인하기

In [2]:
print(cafe.shape)

(12, 7)

In [3]:
print(cafe.columns)

Index(['주문번호', '매장', '메뉴', '종류', '가격_원', '수량_개', '평가'], dtype='str')

## 3단계. 열 선택하기

In [4]:
print(cafe["가격_원"].head())

0    4500
1    5000
2    4800
3    6500
4    4500
Name: 가격_원, dtype: int64

In [5]:
print(cafe[["메뉴", "가격_원", "평가"]].head())

      메뉴  가격_원  평가
0  아메리카노  4500   1
1   카페라테  5000   1
2     녹차  4800  -1
3  치즈케이크  6500  -1
4  아메리카노  4500   1

## 4단계. 조건 검색 — 원하는 행만 골라내기

In [6]:
check = cafe["종류"] == "커피"
print(check.head())

0     True
1     True
2    False
3    False
4     True
Name: 종류, dtype: bool

In [7]:
coffee = cafe[cafe["종류"] == "커피"]
print(coffee.shape)

(5, 7)

In [8]:
pricey = cafe[cafe["가격_원"] > 5000]
print(len(pricey))

5

## 5단계. 조건 검색 — 골라낸 표에서 한 번 더 고르기

In [9]:
bad = cafe[cafe["평가"] == -1]
print(bad.shape)

(4, 7)

In [10]:
pricey_bad = pricey[pricey["평가"] == -1]
print(len(pricey_bad))

3

## 6단계. 정렬하기

In [11]:
cafe.sort_values("가격_원", ascending=False).head(5)

     주문번호   매장     메뉴   종류  가격_원  수량_개  평가
9   C-010  홍대점  초코케이크  디저트  6800     1  -1
3   C-004  강남점  치즈케이크  디저트  6500     1  -1
5   C-006  홍대점  바닐라라테   커피  5500     1  -1
8   C-009  강남점   카페모카   커피  5500     1   1
10  C-011  강남점    유자차    차  5200     1   1

## 7단계. loc 맛보기 — 행 이름과 열 이름으로 값 꺼내기

In [12]:
print(cafe.loc[0, "가격_원"])

4500

In [13]:
coffee_view = cafe.loc[cafe["종류"] == "커피", ["메뉴", "가격_원", "평가"]]
print(coffee_view.head())

      메뉴  가격_원  평가
0  아메리카노  4500   1
1   카페라테  5000   1
4  아메리카노  4500   1
5  바닐라라테  5500  -1
8   카페모카  5500   1

In [14]:
print(cafe.iloc[0:3])

    주문번호   매장     메뉴  종류  가격_원  수량_개  평가
0  C-001  강남점  아메리카노  커피  4500     2   1
1  C-002  홍대점   카페라테  커피  5000     1   1
2  C-003  강남점     녹차   차  4800     1  -1

## 8단계. 따로 떼어 보고 비율 구하기

In [15]:
dessert = cafe[cafe["종류"] == "디저트"]
dessert_bad = dessert[dessert["평가"] == -1]
bad_rate = len(dessert_bad) / len(dessert) * 100

print(f"디저트 별로예요 건수: {len(dessert_bad)}건")
print(f"디저트 별로예요 비율: {bad_rate:.1f}%")

디저트 별로예요 건수: 2건
디저트 별로예요 비율: 50.0%

In [16]:
print(dessert_bad[["주문번호", "메뉴", "가격_원"]])

    주문번호     메뉴  가격_원
3  C-004  치즈케이크  6500
9  C-010  초코케이크  6800

## 9단계. 반도체 데이터 실습 — 읽기와 열 선택

### 문제 1 — 반도체 데이터 읽기

In [17]:
df = pd.read_csv("../../data/weekly/week04/week04_process_filtering.csv", encoding="utf-8-sig")
df.head()

               측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
0  2024-03-01 21:00  LOT-0141  EQ-02  산화  297.6  1005.8     50.02     1
1  2024-03-02 04:00  LOT-0122  EQ-04  식각  300.4  1010.5     49.22     1
2  2024-03-02 08:00  LOT-0156  EQ-02  세정  296.9  1007.6     50.91    -1
3  2024-03-02 12:00  LOT-0224  EQ-02  산화  297.2  1019.1     47.75     1
4  2024-03-02 21:00  LOT-0302  EQ-01  세정  296.7  1016.9     51.17     1

### 문제 2 — 크기와 열 이름

In [18]:
print(df.shape)

(100, 8)

In [19]:
print(df.columns)

Index(['측정시간', '로트번호', '설비번호', '공정명', '온도_섭씨', '압력_Pa', '가스유량_slm', '합격여부'], dtype='str')

### 문제 3 — 열 선택

In [20]:
print(df["온도_섭씨"].head())

0    297.6
1    300.4
2    296.9
3    297.2
4    296.7
Name: 온도_섭씨, dtype: float64

In [21]:
print(df[["설비번호", "온도_섭씨", "합격여부"]].head())

    설비번호  온도_섭씨  합격여부
0  EQ-02  297.6     1
1  EQ-04  300.4     1
2  EQ-02  296.9    -1
3  EQ-02  297.2     1
4  EQ-01  296.7     1

## 10단계. 반도체 데이터 실습 — 조건 검색

### 문제 4 — EQ-02 기록만 고르기

In [22]:
check = df["설비번호"] == "EQ-02"
print(check.head())

0     True
1    False
2     True
3     True
4    False
Name: 설비번호, dtype: bool

In [23]:
eq02 = df[df["설비번호"] == "EQ-02"]
print(eq02.shape)

(25, 8)

### 문제 5 — 305도 초과 기록

In [24]:
hot = df[df["온도_섭씨"] > 305]
print(len(hot))

13

### 문제 6 — 불합격, 고온 중 불합격

In [25]:
fail = df[df["합격여부"] == -1]
print(fail.shape)

(13, 8)

In [26]:
hot_fail = hot[hot["합격여부"] == -1]
print(len(hot_fail))

3

## 11단계. 반도체 데이터 실습 — 정렬과 loc

### 문제 7 — 온도 상위 5건

In [27]:
df.sort_values("온도_섭씨", ascending=False).head(5)

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
30  2024-03-11 18:00  LOT-0324  EQ-03  포토  310.1  1010.0     51.55     1
15  2024-03-06 16:00  LOT-0089  EQ-03  증착  308.6  1006.8     51.56     1
57  2024-03-20 03:00  LOT-0159  EQ-01  증착  308.4  1014.4     51.59     1
40  2024-03-13 15:00  LOT-0174  EQ-04  증착  308.4  1008.8     49.92     1
11  2024-03-05 12:00  LOT-0192  EQ-04  증착  308.2  1033.0     52.46    -1

### 문제 8 — loc으로 꺼내기

In [28]:
print(df.loc[0, "온도_섭씨"])

297.6

In [29]:
eq02_view = df.loc[df["설비번호"] == "EQ-02", ["로트번호", "온도_섭씨", "합격여부"]]
print(eq02_view.head())

        로트번호  온도_섭씨  합격여부
0   LOT-0141  297.6     1
2   LOT-0156  296.9    -1
3   LOT-0224  297.2     1
8   LOT-0054  294.4     1
14  LOT-0375  303.4     1

## 12단계. 반도체 데이터 실습 — 따로 떼어 보고 비율 구하기

### 문제 9 — EQ-02 불합격률

In [30]:
eq02 = df[df["설비번호"] == "EQ-02"]
eq02_fail = eq02[eq02["합격여부"] == -1]
fail_rate = len(eq02_fail) / len(eq02) * 100

print(f"EQ-02 불합격 건수: {len(eq02_fail)}건")
print(f"EQ-02 불합격률: {fail_rate:.1f}%")

EQ-02 불합격 건수: 5건
EQ-02 불합격률: 20.0%

### 문제 10 — 불합격 기록 여러 열 함께 보기

In [31]:
print(eq02_fail[["로트번호", "공정명", "온도_섭씨"]])

        로트번호 공정명  온도_섭씨
2   LOT-0156  세정  296.9
21  LOT-0074  식각  299.3
44  LOT-0218  식각  304.9
84  LOT-0217  증착  301.4
85  LOT-0162  세정  307.8

### 문제 11 — EQ-04와 비교

In [32]:
eq04 = df[df["설비번호"] == "EQ-04"]
eq04_fail = eq04[eq04["합격여부"] == -1]
eq04_rate = len(eq04_fail) / len(eq04) * 100

print(f"EQ-04 불합격 건수: {len(eq04_fail)}건")
print(f"EQ-04 불합격률: {eq04_rate:.1f}%")

EQ-04 불합격 건수: 5건
EQ-04 불합격률: 22.7%

## 13단계. AI에게 질문하며 더 알아보기

## 14단계. AI에게 코드 생성 요청하고 직접 실행해보기

In [33]:
summary = pd.crosstab(df["설비번호"], df["합격여부"])
print(summary)

합격여부   -1   1
설비번호
EQ-01   2  29
EQ-02   5  20
EQ-03   1  21
EQ-04   5  17