# 3주차 강사용 Notebook — Pandas로 공정 데이터 읽고 선택하기

학생용 Notebook과 동일한 흐름이며, 예상 결과와 설명 포인트를 함께 담았습니다.

## 1단계. Pandas 불러오기

In [1]:
import pandas as pd
print('Pandas 준비 완료')

Pandas 준비 완료

## 2단계. 데이터 읽기
**설명 포인트**: `read_csv`의 인자가 파일 경로임을 강조. Colab에서는 업로드 후 파일명만 적으면 된다는 점을 시연.

In [2]:
df = pd.read_csv("../../data/weekly/week03/week03_process_filtering.csv")
df.head()

               측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
0  2024-03-01 00:00  LOT-0217  EQ-01  산화  297.5  1002.7     51.20     1
1  2024-03-01 03:00  LOT-0230  EQ-03  산화  297.1   988.5     48.33     1
2  2024-03-01 06:00  LOT-0231  EQ-02  포토  295.9  1000.7     47.47     1
3  2024-03-01 12:00  LOT-0220  EQ-02  증착  296.3  1007.2     54.65     1
4  2024-03-01 16:00  LOT-0303  EQ-02  증착  301.5   999.1     47.28     1

**예상 결과**: 8개 열(측정시간, 로트번호, 설비번호, 공정명, 온도_섭씨, 압력_Pa, 가스유량_slm, 합격여부)이 보임. 총 100행 8열.

## 3단계. 열 선택하기
**어려워할 부분**: 여러 열을 선택할 때 대괄호를 한 번만 써서 오류를 겪는 학생이 많음.
`df[['온도_섭씨', '압력_Pa']]`처럼 바깥 대괄호(선택 문법) + 안쪽 대괄호(리스트)가 필요함을 강조.

In [3]:
df["온도_섭씨"]

df[["온도_섭씨", "압력_Pa"]]

    온도_섭씨   압력_Pa
0   297.5  1002.7
1   297.1   988.5
2   295.9  1000.7
3   296.3  1007.2
4   301.5   999.1
..    ...     ...
95  298.4  1003.0
96  301.5  1012.4
97  300.3  1011.3
98  302.3   995.3
99  296.6  1011.4

[100 rows x 2 columns]

**예상 결과**: 첫 번째는 Series(1개 열), 두 번째는 DataFrame(2개 열)이 출력됨.

In [4]:
df.dtypes

측정시간         object
로트번호         object
설비번호         object
공정명          object
온도_섭씨       float64
압력_Pa       float64
가스유량_slm    float64
합격여부          int64
dtype: object

**예상 결과**: `온도_섭씨`, `압력_Pa`, `가스유량_slm`은 `float64`, `합격여부`는 `int64`,
나머지 문자열 열은 `object`.

## 4단계. 조건 검색 — 특정 설비 찾기
**칠판 포인트**: `=`(저장)과 `==`(비교)를 나란히 적어 구분해서 설명.

In [5]:
eq02 = df[df["설비번호"] == "EQ-02"]
print(eq02.shape)

(32, 8)

**예상 결과**: `(32, 8)` — EQ-02 공정 기록은 32건.

## 5단계. 불합격 행 찾기
**설명 포인트**: 4단계에서 만든 `eq02` 위에 조건을 한 번 더 적용하는 것을 보여준다
(조건 검색을 이어서 적용할 수 있다는 감각).

In [6]:
fail_eq02 = eq02[eq02["합격여부"] == -1]
fail_eq02[["측정시간", "로트번호", "공정명", "합격여부"]]

                측정시간      로트번호 공정명  합격여부
13  2024-03-04 09:00  LOT-0203  산화    -1
37  2024-03-11 09:00  LOT-0128  식각    -1
52  2024-03-16 11:00  LOT-0228  산화    -1
59  2024-03-19 06:00  LOT-0032  식각    -1
60  2024-03-19 18:00  LOT-0237  산화    -1
83  2024-03-28 12:00  LOT-0365  세정    -1
90  2024-03-31 13:00  LOT-0219  세정    -1
97  2024-04-03 04:00  LOT-0376  증착    -1

**예상 결과**: 8건이 출력됨. 8 ÷ 32 × 100 = 25.0%.
전체 데이터에서 EQ-02가 아닌 나머지 설비의 불합격 비율(5.9%)과 비교해 설명한다.

## 6단계. 온도 기준으로 정렬하기
**어려워할 부분**: `ascending=False`를 빠뜨리면 오름차순으로 정렬된다는 것을 모를 수 있음.

In [7]:
df.sort_values("온도_섭씨", ascending=False).head(5)

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
15  2024-03-05 12:00  LOT-0041  EQ-04  산화  312.4   996.7     51.58     1
40  2024-03-11 22:00  LOT-0362  EQ-02  세정  309.1  1025.4     50.11     1
14  2024-03-05 03:00  LOT-0338  EQ-03  산화  308.9  1024.0     50.01     1
81  2024-03-27 12:00  LOT-0340  EQ-02  증착  308.7  1015.4     51.84     1
89  2024-03-31 10:00  LOT-0399  EQ-03  식각  306.8  1005.2     51.36     1

**예상 결과**: 상위 5건의 로트가 LOT-0041(EQ-04), LOT-0362(EQ-02), LOT-0338(EQ-03),
LOT-0340(EQ-02), LOT-0399(EQ-03) 순으로 나오며, 모두 `합격여부`가 1(합격)이다.
"온도가 높다고 항상 불합격은 아니다"는 점을 짚어준다(8주차 상관관계 논의의 씨앗).

## 7단계. 확장 실습 — 나머지 설비와 비교
**실습 시간 조절**: 시간이 부족하면 이 단계는 숙제로 돌려도 된다.

In [8]:
others = df[df["설비번호"] != "EQ-02"]
fail_rate_eq02 = (eq02["합격여부"] == -1).mean() * 100
fail_rate_others = (others["합격여부"] == -1).mean() * 100
print(f"EQ-02 불합격 비율: {fail_rate_eq02:.1f}%")
print(f"나머지 설비 불합격 비율: {fail_rate_others:.1f}%")

EQ-02 불합격 비율: 25.0%
나머지 설비 불합격 비율: 5.9%

**예상 결과**: `EQ-02 불합격 비율: 25.0%`, `나머지 설비 불합격 비율: 5.9%`.

## 8단계. 오류 대처 방법
- `KeyError` 발생 시: `df.columns`로 정확한 열 이름 확인.
- `SyntaxError`(조건식에 `=` 사용) 발생 시: `==`로 고치도록 안내.
- 필터 결과가 빈 표로 나오면: 문자열 대소문자·띄어쓰기(`"EQ-02"`)가 정확한지 확인.

## 확장 실습(빠른 학습자용)
`&`로 조건 두 개를 동시에 적용해보게 하면 4주차(결측값 필터링) 예고가 된다.

In [9]:
df[(df["설비번호"] == "EQ-02") & (df["합격여부"] == -1)]

                측정시간      로트번호   설비번호 공정명  온도_섭씨   압력_Pa  가스유량_slm  합격여부
13  2024-03-04 09:00  LOT-0203  EQ-02  산화  291.7   999.9     52.42    -1
37  2024-03-11 09:00  LOT-0128  EQ-02  식각  303.8  1026.5     51.49    -1
52  2024-03-16 11:00  LOT-0228  EQ-02  산화  301.6  1015.3     48.85    -1
59  2024-03-19 06:00  LOT-0032  EQ-02  식각  295.3  1008.7     50.50    -1
60  2024-03-19 18:00  LOT-0237  EQ-02  산화  298.9  1009.3     52.53    -1
83  2024-03-28 12:00  LOT-0365  EQ-02  세정  303.6  1016.1     48.22    -1
90  2024-03-31 13:00  LOT-0219  EQ-02  세정  296.3  1007.7     50.96    -1
97  2024-04-03 04:00  LOT-0376  EQ-02  증착  300.3  1011.3     49.23    -1